"""
Pydantic models for all Kafka message types.
Provides JSON-schema export and validation for inter-service communication.
"""

from datetime import datetime
from enum import Enum
from typing import Optional
from pydantic import BaseModel, Field, ConfigDict

from evcharging.common.utils import utc_now


class MessageStatus(str, Enum):
    """Status codes for driver request updates."""
    ACCEPTED = "accepted"
    DENIED = "denied"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    FAILED = "failed"


class CommandType(str, Enum):
    """Command types that Central can send to CP_E."""
    START_SUPPLY = "start_supply"
    STOP_SUPPLY = "stop_supply"
    STOP_CP = "stop_cp"
    RESUME_CP = "resume_cp"
    SHUTDOWN = "shutdown"


class DriverRequest(BaseModel):
    """Request from driver to charge at a specific CP."""
    request_id: str = Field(..., description="Unique request identifier")
    driver_id: str = Field(..., description="Driver identifier")
    cp_id: str = Field(..., description="Charging point identifier")
    ts: datetime = Field(default_factory=utc_now, description="Timestamp")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "request_id": "req-001",
                "driver_id": "driver-123",
                "cp_id": "CP-001",
                "ts": "2025-10-13T12:00:00Z"
            }
        }
    )


class DriverUpdate(BaseModel):
    """Status update sent back to driver."""
    request_id: str = Field(..., description="Original request identifier")
    driver_id: str = Field(..., description="Driver identifier")
    cp_id: str = Field(..., description="Charging point identifier")
    status: MessageStatus = Field(..., description="Current status")
    reason: Optional[str] = Field(None, description="Additional information or error reason")
    session_id: Optional[str] = Field(None, description="Session identifier assigned by Central")
    ts: datetime = Field(default_factory=utc_now, description="Timestamp")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "request_id": "req-001",
                "driver_id": "driver-123",
                "cp_id": "CP-001",
                "status": "in_progress",
                "reason": "Charging started",
                "ts": "2025-10-13T12:00:01Z"
            }
        }
    )


class CentralCommand(BaseModel):
    """Command from Central to CP_E."""
    cmd: CommandType = Field(..., description="Command type")
    cp_id: str = Field(..., description="Target charging point")
    payload: Optional[dict] = Field(None, description="Additional command data")
    ts: datetime = Field(default_factory=utc_now, description="Timestamp")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "cmd": "start_supply",
                "cp_id": "CP-001",
                "payload": {"driver_id": "driver-123", "request_id": "req-001"},
                "ts": "2025-10-13T12:00:00Z"
            }
        }
    )


class CPStatus(BaseModel):
    """Status report from CP_E to Central."""
    cp_id: str = Field(..., description="Charging point identifier")
    state: str = Field(..., description="Current CP state")
    reason: Optional[str] = Field(None, description="State change reason")
    ts: datetime = Field(default_factory=utc_now, description="Timestamp")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "cp_id": "CP-001",
                "state": "SUPPLYING",
                "reason": "Driver request accepted",
                "ts": "2025-10-13T12:00:01Z"
            }
        }
    )


class CPTelemetry(BaseModel):
    """Real-time telemetry from CP_E during charging session."""
    cp_id: str = Field(..., description="Charging point identifier")
    kw: float = Field(..., description="Current power delivery in kW")
    kwh: float = Field(..., description="Cumulative energy delivered in kWh")
    euros: float = Field(..., description="Cumulative cost in euros")
    driver_id: Optional[str] = Field(None, description="Current driver (non-personal demo ID)")
    session_id: Optional[str] = Field(None, description="Current charging session ID")
    ts: datetime = Field(default_factory=utc_now, description="Timestamp")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "cp_id": "CP-001",
                "kw": 22.5,
                "kwh": 1.2,
                "euros": 3.75,
                "driver_id": "driver-123",
                "session_id": "session-001",
                "ts": "2025-10-13T12:00:05Z"
            }
        }
    )

class CPSessionTicket(BaseModel):
    """
    Final session summary generated by a Charging Point (CP_E) 
    when a charging session ends
    """
    
    cp_id: str = Field(..., description="Charging point identifier")
    session_id: str = Field(..., description="Charging session identifier")
    driver_id: str = Field(..., description="Driver involved in the session")
    start_time: datetime = Field(..., description="When the charging session began")
    end_time: datetime = Field(default_factory=utc_now,
                               description="When the charging session ended")
    energy_kwh: float = Field(..., description="Total delivered energy in kWh")
    total_cost_eur: float = Field(..., description="Total cost accumulated in euros")
    ts: datetime = Field(default_factory=utc_now,
                         description="Timestamp when the ticket was created by CP_E")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "cp_id": "CP-003",
                "session_id": "sess-0007",
                "driver_id": "driver-eve",
                "start_time": "2025-11-07T14:32:00Z",
                "end_time": "2025-11-07T14:42:00Z",
                "energy_kwh": 5.37,
                "total_cost_eur": 1.61,
                "ts": "2025-11-07T14:42:01Z"
            }
        }
    )


class CPRegistration(BaseModel):
    """CP Monitor registration message to Central."""
    cp_id: str = Field(..., description="Charging point identifier")
    cp_e_host: str = Field(..., description="CP Engine host")
    cp_e_port: int = Field(..., description="CP Engine port")
    ts: datetime = Field(default_factory=utc_now, description="Timestamp")


def get_json_schemas() -> dict:
    """Export JSON schemas for all message types."""
    return {
        "DriverRequest": DriverRequest.model_json_schema(),
        "DriverUpdate": DriverUpdate.model_json_schema(),
        "CentralCommand": CentralCommand.model_json_schema(),
        "CPStatus": CPStatus.model_json_schema(),
        "CPTelemetry": CPTelemetry.model_json_schema(),
        "CPRegistration": CPRegistration.model_json_schema(),
    }


class WeatherReport(BaseModel):
    """
    Weather report generated by EV_Weather component
    """
    
    city: str = Field(..., description="City which the report describes")
    temperature: float = Field(..., description="Value of the temperature in the given city")
    alert: bool = Field(..., description="Is the value of the temperature lower than 0 Celsius degree")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "city": "Poznan",
                "temperature": 5.3,
                "alert": False,
            }
        }
    )


class ErrorCategory(str, Enum):
    """Categories of system errors."""
    CONNECTION = "CONNECTION"           # Network connectivity issues
    COMMUNICATION = "COMMUNICATION"     # Message parsing/protocol errors
    CP_UNAVAILABLE = "CP_UNAVAILABLE"   # CP out of service
    AUTHENTICATION = "AUTHENTICATION"   # Security/credential errors
    SERVICE = "SERVICE"                 # External service failures
    SESSION = "SESSION"                 # Charging session errors
    SYSTEM = "SYSTEM"                   # Internal system errors


class ErrorSeverity(str, Enum):
    """Severity levels for errors."""
    INFO = "INFO"
    WARNING = "WARNING"
    ERROR = "ERROR"
    CRITICAL = "CRITICAL"


class SystemErrorMessage(BaseModel):
    """
    System error message for inter-service communication.
    Used to propagate errors between Central, CPs, and Driver front-end.
    """
    error_id: str = Field(..., description="Unique error identifier")
    category: ErrorCategory = Field(..., description="Error category")
    severity: ErrorSeverity = Field(default=ErrorSeverity.ERROR, description="Error severity")
    source: str = Field(..., description="Component that generated the error")
    target: str = Field(..., description="Affected component or resource")
    message: str = Field(..., description="User-friendly error message")
    technical_detail: Optional[str] = Field(None, description="Technical details for debugging")
    resolved: bool = Field(default=False, description="Whether error has been resolved")
    ts: datetime = Field(default_factory=utc_now, description="Error timestamp")

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "error_id": "ERR-000001",
                    "category": "CONNECTION",
                    "severity": "ERROR",
                    "source": "CENTRAL",
                    "target": "CP-001",
                    "message": "Unable to connect to CP CP-001. Messages are incomprehensible.",
                    "technical_detail": "JSON parse error at position 42",
                    "resolved": False,
                    "ts": "2025-12-22T12:00:00Z"
                },
                {
                    "error_id": "ERR-000002",
                    "category": "CP_UNAVAILABLE",
                    "severity": "WARNING",
                    "source": "CENTRAL",
                    "target": "CP-002",
                    "message": "CP CP-002 not available. CP out of service.",
                    "resolved": False,
                    "ts": "2025-12-22T12:00:00Z"
                },
                {
                    "error_id": "ERR-000003",
                    "category": "SERVICE",
                    "severity": "ERROR",
                    "source": "WEATHER",
                    "target": "OpenWeather",
                    "message": "Unable to access the weather. OpenWeather connection unavailable.",
                    "resolved": False,
                    "ts": "2025-12-22T12:00:00Z"
                }
            ]
        }
    )


class ErrorNotification(BaseModel):
    """
    Error notification sent to front-end clients (Driver dashboard).
    Contains display-ready error information.
    """
    error_id: str = Field(..., description="Unique error identifier")
    title: str = Field(..., description="Short error title for display")
    message: str = Field(..., description="Full error message")
    severity: ErrorSeverity = Field(default=ErrorSeverity.ERROR, description="Error severity")
    category: ErrorCategory = Field(..., description="Error category")
    source: str = Field(..., description="Source component")
    can_retry: bool = Field(default=False, description="Whether user can retry the operation")
    is_resolved: bool = Field(default=False, description="Whether error has been resolved")
    ts: datetime = Field(default_factory=utc_now, description="Notification timestamp")

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "error_id": "ERR-000001",
                "title": "Connection Error",
                "message": "Unable to connect to charging point CP-001.",
                "severity": "ERROR",
                "category": "CONNECTION",
                "source": "CENTRAL",
                "can_retry": True,
                "is_resolved": False,
                "ts": "2025-12-22T12:00:00Z"
            }
        }
    )